module.exports = [
  ['/uploadImage', 'common/uploadImage'],
  ['/sendMail', 'common/sendMail'],
  ['/login', 'user/login'],
  ['/register', 'user/register'],
  ['/signOut', 'user/signOut'],
  ['/home', 'home/get'],
  ['/list', 'list/get'],
  ['/list/newPost', 'list/newPost'],
  ['/post', 'post/get'],
  ['/post/newComment', 'post/newComment'],
  ['/admin/isAdmin', 'admin/isAdmin'],
  ['/admin/getMenu', 'admin/getMenu'],
  ['/admin/user/get', 'admin/userGet'],
  ['/admin/user/put', 'admin/userPut'],
  ['/admin/label/get', 'admin/labelGet'],
  ['/admin/label/put', 'admin/labelPut'],
  ['/admin/label/add', 'admin/labelAdd'],
  ['/admin/permission/get', 'admin/permissionGet'],
  ['/admin/permission/put', 'admin/permissionPut'],
  ['/admin/list/:url/get', 'admin/listGet'],
  ['/admin/list/:url/put', 'admin/listPut'],
  ['/user/getPost', 'user/getPost'],
  ['/user/getComment', 'user/getComment'],
  ['/user/getInformation', 'user/getInformation'],
  ['/user/setting', 'user/setting'],
  ['/test', 'user/test']
];
